### ISSUE TITLE
Allow selecting payment methods individually 

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-AdobeCommerce-Magento2#28]
We need to allow the merchant to enable/disable individual payment methods in the config settings so they are visible as a list on the checkout page.

This is an example from WooCommerce integration 

<img width="1523" alt="image" src="https://github.com/MONEI/MONEI-AdobeCommerce-Magento2/assets/5391775/8257b31b-bb96-47f7-96a1-fc2534c84b7d">

Checkout:

![2023-09-20 17 39 38](https://github.com/MONEI/MONEI-AdobeCommerce-Magento2/assets/5391775/b730388e-ea4b-48cc-97b1-be3bb4a35308)

The full list of supported payment methods can be found here - https://docs.monei.com/api/#operation/payments_create

<img width="797" alt="image" src="https://github.com/MONEI/MONEI-AdobeCommerce-Magento2/assets/5391775/b4b9293c-c940-4d80-bfc9-e34b7d45099a">

When the payment method is selected, the payment is created with `allowedPaymentMethods: [selectedPaymentMethod]`

This way, the user will be redirected to the selected payment method without going through the hosted payment page. 

In the first iteration, it will be enough to implement redirect flow for each payment method (similar to what is implemented now)

In the second iteration, we need to integrate [UI Components](https://docs.monei.com/docs/integrations/build-custom-checkout/) for all supported payment methods and process the payment without redirect

Here you can find an example of existing PrestaShop store - https://www.nitro-pc.es/

<img width="991" alt="image" src="https://github.com/MONEI/MONEI-AdobeCommerce-Magento2/assets/5391775/9e6e1ab5-c125-469c-9350-2d990ddf5935">

**Comment by alexandresaiz** [comment]
@jimmyn can we assign this issue to the right developer?
