### ISSUE TITLE
Incorrect order status after payment success

### ISSUE THREAD

**Issue by samoritano** [MONEI/MONEI-AdobeCommerce-Magento2#34]
Hi there.

We recently updated the plugin to its latest version, in order to test insite payments (which work really great! 🚀), but we saw that now all new successful orders are being created in "`Monei - Payment Success`" status, instead of the expected "`Processing`" status (the one selected on our config).

We already noticed this problem in prior versions of the plugin and also reported it to Monei support team, and had to develop a workarond , and we ended developing a cron script for changing the status programatically. And you guys solved this issue in version 1.1.9 (if I remember correctly)

Now we see that this wrong status has been reverted, and all new orders are created in "`Monei - Payment Success`".

**Comment by jimmyn** [comment]
Hi @samoritano could you please upgrade to the latest version. Is this issue resolved?

**Comment by samoritano** [comment]
Hi, @jimmyn .

Yes, I have tested the latest version and the problem seems to be resolved.

Thank you very much.

**Comment by samoritano** [comment]
Hi, it seems this issue has been reverted, since we are already getting the "Money - Payment Success" status with the latest version.

We think the problem only appears with the Paypal payment type, not credit card.

**Comment by jimmyn** [comment]
Hello @samoritano the issue should be solved in the latest version
